# Generated by Django 2.2.6 on 2019-11-03 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationid', models.IntegerField()),
                ('city', models.TextField()),
                ('street', models.TextField()),
                ('state', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PayingGuestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nearestLandmark', models.TextField()),
                ('no_of_beds', models.IntegerField()),
                ('price', models.IntegerField()),
                ('gst', models.IntegerField()),
                ('wifi_no_wifi', models.CharField(max_length=100)),
                ('ac_no_ac', models.CharField(max_length=100)),
                ('male_or_female', models.CharField(max_length=100)),
                ('publishedDate', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payingGuestApp.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationBooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.TextField()),
                ('notification_date', models.DateField()),
                ('payingGuestDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payingGuestApp.PayingGuestDetails')),
            ],
        ),
    ]
