# Generated by Django 2.2.6 on 2019-11-03 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payingGuestApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='locationid',
        ),
        migrations.RemoveField(
            model_name='location',
            name='street',
        ),
    ]
