# Generated by Django 2.2.6 on 2019-11-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payingGuestApp', '0003_auto_20191103_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payingguestdetails',
            name='ac_no_ac',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payingguestdetails',
            name='male_or_female',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payingguestdetails',
            name='wifi_no_wifi',
            field=models.IntegerField(),
        ),
    ]
